# Netlify build configuration
[build]
  # Set the base directory to our frontend folder
  base    = "frontend"
  # This command is now run from within the 'base' directory
  command = "npm run build"
  # The publish directory is relative to the 'base' directory
  publish = "dist"

# Netlify functions configuration
[functions]
  directory = "netlify/functions"

# Netlify dev server configuration
[dev]
  command = "npm run dev --prefix frontend"
  targetPort = 5173

# Redirect rule for Single-Page Applications (SPA)
# This is crucial for things like Netlify Identity's email links to work.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200